
# This is a basic workflow to help you get started with Actions
name: Build dependencies 

# Controls when the workflow will run
on: workflow_dispatch
  
jobs:
  # This workflow contains a single job called "build"
  build:
    #if: github.ref_name == 'zicky-eng-patch-1'
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: Get kubectl file
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"

      - name: Download Pulumi
        run: |
          wget https://get.pulumi.com/releases/sdk/pulumi-v3.94.0-linux-x64.tar.gz
      - name: Check AWS CLI version
        run: |
          aws --version
      - name: Get first name
        run: echo "my first name is ${{ var.FIRST_NAME }}"
        #   curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        #  unzip awscliv2.zip
        #  sudo ./aws/install
          #aws --version
      # Runs a set of commands using the runners shell
      #- name: Run a multi-line script
      #  run: |
      #    echo Add other actions to build,
      #    echo test, and deploy your project.
