
# This is a basic workflow to help you get started with Actions
name: Build dependencies 

# Controls when the workflow will run
on: workflow_dispatch
  
jobs:
  # This workflow contains a single job called "build"
  build:
    #if: github.ref_name == 'zicky-eng-patch-1'
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
     # - name: Get kubectl file
     #   run: |
     #     curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"

      - name: Download Pulumi
        run: |
          wget https://get.pulumi.com/releases/sdk/pulumi-v3.94.0-linux-x64.tar.gz
      - name: Upload Pulumi dependency to S3
        env: 
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "us-east-1"
          BUCKET: "testpulumibucket"
        run: |
          aws s3 cp --no-progress pulumi-v3.94.0-linux-x64.tar.gz s3://$BUCKET/
